### ISSUE TITLE
[Bug] /pass for deactivation, and possibly activation of the device is heard globally

### ISSUE THREAD

**Issue by ResqDiver1317** [inferno-collection/Pass-Alarm#5]
**Describe the bug**
Pretty much everytime (or at least everytime I'm actually watching chat) when one of us turns off our PASS device, we see messages in chat from people nowhere near us asking what that noise was. It doesn't seem to be an issue with stage 1 or stage 2 and I'm not 100% sure on the Activation as I'm not usually watching chat at this point as I'm trying to get geared up to go into the fire but almost every time we turn our devices off after we come out, we see messages in chat about it. 
**Steps to reproduce**
We were working a fire at Yellowjack at Panorama and Route 68 and had 8 FFs all in the fire working it. As they made their way out and started turning off their PASS devices, there were people in Paleto Bay and Grapeseed asking in chat what all the beeping was about. We have had issues trying to determine if it is everytime or not as at this point, many of our players know what the sound is and just ignore it so when we have tried to test to see if anyone notices, we do not get questions everytime but moreoften than not, we will get people asking.
**Expected behavior**
Sound should only be heard in a relatively short radius as would be expected IRL.
**Screenshots**

**Resource version**
1.2 Beta
**Additional context**

**Comment by cm8263** [comment]
This issues arrises from the way we handle ([or perhaps more accurately, mishandle](https://github.com/inferno-collection/Pass-Alarm/blob/0443a1699165c69169b341392b3b9f6e20b2a125/%5Binferno-collection%5D/inferno-pass-alarm/html/index.html#L38)) the deactivation sound. While all other sounds that are played are able to use the [volume loop](https://github.com/inferno-collection/Pass-Alarm/blob/0443a1699165c69169b341392b3b9f6e20b2a125/%5Binferno-collection%5D/inferno-pass-alarm/client.lua#L96), this one can not, because the sound is removed from the server table, and all client tables before the sound has a chance to be played. During early development, we resolved this issue by simply having it play full volume, and clearly we've forgotten about that and it's make it into the public release. This is a major oversight on our behalf, so apologies about that; we'll look into creating a fix for Version 1.31 which is due to release this weekend; in the meantime, my suggestion is to change [this line](https://github.com/inferno-collection/Pass-Alarm/blob/0443a1699165c69169b341392b3b9f6e20b2a125/%5Binferno-collection%5D/inferno-pass-alarm/html/index.html#L44) to `0.0`, which will remove the sound for everyone.

Thanks for pointing this out!

**Comment by cm8263** [comment]
Fixed in https://github.com/inferno-collection/Pass-Alarm/commit/7ded8f2db88bbd40df2198f94e1f276f477d1f6a.
